version: "3"
services:
  server:
    image: argishtyfirst/server:latest
    container_name: server
    ports:
      - "9609:9609"
  ui:
    image: argishtyfirst/ui:latest
    container_name: ui
    ports:
      - "3000:80"
